spring.application.name=catalog-service
server.port=8081

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging basico
logging.level.root=INFO
logging.level.org.springframework=INFO