spring.datasource.url=jdbc:postgresql://localhost:5433/guardian_catalog
spring.datasource.username=guardian
spring.datasource.password=guardian

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration